name: color_palette
version: 0.0.1
description: A custom element to pick colors
author: Keiichiro Ui <keiichiro.ui@gmail.com>
dependencies:
  polymer: '>=0.11.0 <0.12.0'
dev_dependencies:
  ghpages_generator: any
transformers:
- polymer