name: color_palette
version: 1.3.1
author: Keiichiro Ui <keiichiro.ui@gmail.com>
description: A Polymer.dart custom element to pick colors
homepage: https://github.com/kui/color_palette
environment:
  sdk: '>=1.11.0'
dependencies:
  polymer: '>=0.16.1 <0.17.0'
dev_dependencies:
  ghpages_generator: '>=0.3.0 <0.4.0'
transformers:
- polymer:
    entry_points:
    - example/index.html
