name: color_palette
version: 0.2.0
description: A custom element to pick colors
author: Keiichiro Ui <keiichiro.ui@gmail.com>
homepage: https://github.com/kui/color_palette
dependencies:
  polymer: '>=0.11.0 <0.12.0'
dev_dependencies:
  ghpages_generator: '>=0.2.0 <0.3.0'
  path: '>=1.2.0 <1.3.0'
transformers:
- polymer:
    entry_points:
    - example/index.html
